export const COPY = {
  appName: "Spicy Pic",
  tabs: {
    mint: "Mint Spicy Pic",
    collection: "My Collection",
  },
  wallet: {
    connect: "Connect wallet",
    required: "Connect a TON wallet to continue.",
    wrongNetwork: "This Mini App is configured for TON {chain}. Switch network in your wallet and try again.",
  },
  mint: {
    title: "Mint Spicy Pic",
    subtitle: "Limited drops. Public preview, private full-res after mint.",
    empty: "No mintable items are available right now.",
    loading: "Loading minting feed…",
    price: "Mint price",
    supply: "Supply",
    attributes: "Attributes",
    endsIn: "Ends in",
    ended: "Mint ended",
    soldOut: "Sold out",
    action: "Mint",
    signing: "Requesting mint signature…",
    broadcasting: "Confirm the transaction in your wallet…",
    success: "Mint transaction sent. It will appear in My Collection after confirmation.",
    failed: "Mint failed. Please try again.",
    rejected: "Transaction was cancelled in the wallet.",
    connectFirst: "Connect your wallet before minting.",
    unavailable: "This item cannot be minted right now.",
  },
  collection: {
    title: "My Collection",
    subtitle: "Private images for NFTs you own in this collection.",
    empty: "You do not own any NFTs from this collection yet.",
    loading: "Scanning your collection…",
    loadImage: "Loading private image…",
    imageError: "Private image could not be loaded.",
    save: "Save Image",
    saving: "Preparing download…",
    saved: "Image saved.",
    saveFailed: "Could not save the image. Try again.",
    connectPrompt: "Connect your wallet to view owned NFTs.",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    metadata: "Could not load NFT metadata.",
    chain: "Could not read on-chain collection data.",
    signature: "Could not generate a mint signature.",
    invalidAddress: "Wallet address is invalid.",
    invalidIndex: "NFT index is invalid.",
    invalidUrl: "Metadata URL is not allowed.",
    unauthorized: "Server secrets are not configured.",
    proxy: "Could not load the private image.",
  },
  status: {
    testnet: "TON Testnet",
    mainnet: "TON Mainnet",
  },
} as const;
